.TH "kalcatel" "1" "0.2.1" "Michal Cihar" ""
.SH "NAME"
.LP 
kalcatel \- program to work with Alcatel 50x and 70x mobile
.SH "SYNTAX"
.LP 
kalcatel
.SH "DESCRIPTION"
.LP 
This application allows you to manage messages, calls, contacs, todos and
calendar in your Alcatel One Touch 50x and 70x mobile. In fact currently is in
this gui supported just reading of some of them but full functionality will be
coded in future.

Protocol used by this phone is binary and not documented, so this program
could not guarantee any functionality in your case, but it works well for me.
.SH "OPTIONS"
The programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options are included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.SH "FILES"
.LP 
\fI$KDEHOME/share/config/kalcatelrc\fP 
.SH "EXAMPLES"
.LP 
To run this program the standard way type:
.LP 
kalcatel
.SH "AUTHORS"
.LP 
Michal Cihar <cihar@email.cz>
.SH "SEE ALSO"
.LP 
minicom(1), kandy(1)
